"""Immutable governance contracts and non-authoritative replay tokens."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Mapping

from .canonical import CANONICALIZATION_VERSION, canonical_sha256, canonicalize_json

REPLAY_ACTION_KIND = "REPLAY_FIXTURE"
REPLAY_CAPABILITY = "REPLAY"
REPLAY_SCOPE = "REPLAY_ONLY_NON_CRYPTOGRAPHIC"
DEFAULT_POLICY_VERSION = "osiris-governance/v0.1-replay"
DEFAULT_ISSUER = "local-replay-governor"


@dataclass(frozen=True)
class ActionProposal:
    """Canonical proposal generated by a proposer. Grants zero execution authority."""
    proposal_id: str
    request_id: str
    proposer_id: str
    action_kind: str
    capability: str
    fixture_id: str
    arguments: Mapping[str, Any]
    nonce: str
    created_at_utc: str
    expires_at_utc: str
    schema_version: str = "action-proposal/v1"

    def canonical_bytes(self) -> bytes:
        """Serializes proposal into deterministic canonical bytes."""
        return canonicalize_json(asdict(self))

    def proposal_sha256(self) -> str:
        """Computes SHA-256 digest over the proposal canonical bytes."""
        return canonical_sha256(self.canonical_bytes())


@dataclass(frozen=True)
class ReplayExecutionPermit:
    """Non-authoritative token permitting in-memory lookup of a verified replay fixture.
    
    CRITICAL SECURITY NOTICE:
    This object is NOT a cryptographic signature, credential, or real-world authorization.
    Its scope is strictly REPLAY_ONLY_NON_CRYPTOGRAPHIC. It is invalid for filesystem writes,
    subprocesses, network access, cloud execution, trading, or state mutation.
    """
    proposal_sha256: str
    canonicalization_version: str
    policy_version: str
    fixture_id: str
    nonce: str
    process_epoch_id: str
    issued_at_utc: str
    expires_at_utc: str
    scope: str = REPLAY_SCOPE
    issuer: str = DEFAULT_ISSUER


def require_replay_only_permit(permit: ReplayExecutionPermit) -> None:
    """Mechanically asserts that a permit carries strictly the replay-only scope."""
    if permit.scope != REPLAY_SCOPE:
        from .errors import ScopeViolation
        raise ScopeViolation(
            f"Permit scope '{permit.scope}' is unauthorized (must be '{REPLAY_SCOPE}')"
        )


def prohibit_external_execution_from_replay_permit(permit: ReplayExecutionPermit) -> None:
    """Prohibits any external execution, cloud dispatch, or mutation from a replay permit."""
    from .errors import ScopeViolation
    raise ScopeViolation(
        "Replay permits cannot authorize external execution, subprocesses, network, or cloud dispatch"
    )


@dataclass(frozen=True)
class ReplayResultRecord:
    """Normalized immutable record of an authorized replay execution."""
    status: str
    proposal_sha256: str
    fixture_id: str
    permit_nonce: str
    process_epoch_id: str
    payload: Mapping[str, Any]
    executed_at_utc: str
    raw_payload_sha256: str = ""
